djangoProject2/djangoProject2/urls.py
from django.contrib import admin
from django.urls import path
from app01 import views

urlpatterns = [
    # 部门管理
    path("admin/", admin.site.urls),
    path("depart/list/", views.depart_list),
    path("depart/add/", views.depart_add),
    path("depart/del/", views.depart_del),
    path("depart/<int:nid>/edit/", views.depart_edit),

    # 用户管理
    path("user/list/", views.user_list),
    path("user/add/", views.user_add),
    path("user/model_from_add/", views.user_model_from_add),
    path("user/<int:nid>/edit/", views.user_edit),
    path("user/<int:nid>/del",views.user_del),
    path("phone/list/",views.phone_list),
    path("phone/add/",views.phone_add),
    path("phone/<int:nid>/edit/",views.phone_edit),
    path("phone/<int:nid>/del/",views.phone_del)

]

djangoProject2/app01/models.py
from django.db import models

class Department(models.Model):
    # 部门表
    # 自动创建id，为主键，自增
    title = models.CharField(verbose_name="标题", max_length=32)
    #显示部门名称而不是部门Department object(3)
    def __str__(self):
        return self.title
# Create your models here.
class USerInfo(models.Model):
    # verbose_name为注释内容,可写可不写
    name = models.CharField(verbose_name="姓名", max_length=16)
    passwd = models.CharField(verbose_name="密码111", max_length=64)
    age = models.IntegerField(verbose_name="年龄")
    # 账户长度为10，小数点有两位
    account = models.DecimalField(verbose_name="账户余额", max_digits=10, decimal_places=2, default=0)
    creat_time = models.DateTimeField(verbose_name="入职时间")
    #下面的时间格式没有时分秒，一般用作入职时间
    #creat_time = models.DateField(verbose_name="入职时间")
    # 给部门ID加上约束，员工所属部门ID只能是已经存在的,to表示要与那个表关联，to_field表示与表中的哪一列关联，生成的列名字是depart_id
    # 一般用ID相关联，大公司有时候用名字比如销售部门，运维部门
    # 级联删除---  on_delete=models.CASCADE 表示部门被删除，所属该部门的员工也会被删除，叫级联删除
    depart = models.ForeignKey(verbose_name="部门", to="Department", to_field="id", on_delete=models.CASCADE)

    # 置空---  null=True,blank=True,on_delete=models.SET_NULL 表示部门删除后，员工所属部门号为null
    # depart=models.ForeignKey(to="Department",to_field="id",null=True,blank=True,on_delete=models.SET_NULL)

    # 设置性别,属于django的约束
    gender_choice = (
        (1, "男"),
        (2, "女"),
    )
    gender = models.SmallIntegerField(verbose_name="性别", choices=gender_choice)

#手机号表格
class PhoneTable(models.Model):
    """ 靓号表"""
    #id = models.IntegerField(verbose_name="ID", primary_key=True)
    #CharField后面一定要跟max_length,存储成charfiled方便后面正则查找
    mobile = models.CharField(verbose_name="手机号", max_length=11)
    #decimal_places=2 小数点后两位
    #null=True, blank=True 允许为空
    price = models.DecimalField(verbose_name="价格", max_digits=5, decimal_places=2)
    level_choice=(
        (1,"高级"),
        (2,"普通")
    )
    leval=models.SmallIntegerField(verbose_name="等级", choices=level_choice,default=2)
    status_choice=(
        (1,"空闲"),
        (2,"售出")
    )
    status=models.SmallIntegerField(verbose_name="状态", choices=status_choice,default=1)

djangoProject2/app01/views.py
from urllib import request
from app01 import models
from django.utils.safestring import mark_safe
from django.core.exceptions import ValidationError
from django.shortcuts import render, redirect
from datetime import datetime
from app01 import models
from django import forms
from app01.models import Department, USerInfo
from django.core.validators import RegexValidator


# Create your views here.
def depart_list(request):
    """部门列表"""
    queryset = models.Department.objects.all()
    return render(request, "depart_list.html", {"queryset": queryset})


def depart_add(request):
    """添加部门"""
    if request.method == "GET":
        return render(request, "depart_add.html")
    title = request.POST.get("title")
    models.Department.objects.create(title=title)
    return redirect("/depart/list/")


def depart_del(request):
    # 获取id
    nid = request.GET.get("nid")
    models.Department.objects.filter(id=nid).delete()
    return redirect("/depart/list/")


def depart_edit(request, nid):
    if request.method == "GET":
        row_object = models.Department.objects.filter(id=nid).first()
        return render(request, "depart_edit.html", {"row_object": row_object})
    title = request.POST.get("title")
    models.Department.objects.filter(id=nid).update(title=title)
    return redirect("/depart/list/")


def user_list(request):
    """用户管理"""
    # 获取所有用户信息
    queryset = models.USerInfo.objects.all()
    # for obj in queryset:
    #     print(obj.name, obj.account, obj.creat_time, obj.depart_id, obj.depart.title)
    return render(request, "user_list.html", {"queryset": queryset})


def user_add(request):
    if request.method == "GET":
        context = {
            "gender_choice": models.USerInfo.gender_choice,
            "depart_list": models.Department.objects.all()
        }
        return render(request, "user_add.html", context)
    name = request.POST.get("user")
    pwd = request.POST.get("pwd")
    age = request.POST.get("age")
    count = request.POST.get("count")
    time = request.POST.get("time")
    sex = request.POST.get("sex")
    bm = request.POST.get("bm")
    models.USerInfo.objects.create(
        name=name,
        passwd=pwd,
        age=age,
        account=count,
        creat_time=time,
        gender=sex,
        depart_id=bm
    )
    return redirect("/user/list/")


class UserMOdelFrom(forms.ModelForm):
    name = forms.CharField(min_length=3, label="用户名")

    class Meta:
        model = models.USerInfo
        fields = ["name", "passwd", "age", "account", "creat_time", "gender", "depart"]

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for name, field in self.fields.items():
            field.widget.attrs = {"class": "form-control", "placeholder": "哈哈哈"}


def user_model_from_add(request):
    if request.method == "GET":
        form = UserMOdelFrom()
        return render(request, "user_model_from_add.html", {"form": form})
    # 数据校验
    form = UserMOdelFrom(data=request.POST)
    if form.is_valid():
        form.save()
        return redirect("/user/list/")
    return render(request, "user_model_from_add.html", {"form": form})


def user_edit(request, nid):
    """ 编辑用户信息，使用modeform来做"""
    # 更新信息而不是新建一个信息，get和post都可以用，代表当前修改用户的id
    row_object = models.USerInfo.objects.filter(id=nid).first()
    if request.method == "GET":
        # 添加默认信息,modefrom把获取的值默认显示出来
        form = UserMOdelFrom(instance=row_object)
        return render(request, "user_edit.html", {"form": form, "nid": nid})
    form = UserMOdelFrom(data=request.POST, instance=row_object)
    if form.is_valid():
        # 默认保存用户输入的数据
        form.save()
        return redirect('/user/list/')
    return render(request, "user_edit.html", {"form": form, "nid": nid})


def user_del(request, nid):
    models.USerInfo.objects.filter(id=nid).delete()
    return redirect("/user/list/")


class PhoneModelForm(forms.ModelForm):
    # 验证一：正则表达式
    # mobile = forms.CharField(
    #     label="手机号",
    #     validators=[RegexValidator(r'^199\d{8}$', '数字必须以199开头且为11为数字')]
    # )
    class Meta:
        model = models.PhoneTable
        # 指定获取字段
        fields = ('mobile', 'price', 'status', 'leval')
        # 获取所有
        # fields = "__all__"
        # 排除字段
        # exclude = ['phone']

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for name, field in self.fields.items():
            field.widget.attrs = {"class": "form-control"}

    # 钩子方法，定义函数clean_字段名，导入RegexValidator模块
    def clean_mobile(self):
        txt_phone = self.cleaned_data['mobile']
        # 手机号不能一样，新添加时找数据库中的手机号，编辑自己时，手机号可以不用修改也能提交,exclude排除自己
        exitsts = models.PhoneTable.objects.exclude(id=self.instance.pk).filter(mobile=txt_phone).exists()
        if exitsts:
            raise ValidationError("手机号存在")
        if len(txt_phone) != 11:
            raise ValidationError("格式错误")
        return txt_phone


def phone_list(request):
    # for i in range(17):
    #    models.PhoneTable.objects.create(mobile=17613882208, price=100,leval=1,status=1)
    # for i in range(200):
    #     models.PhoneTable.objects.filter(leval=1).delete()
    # from app01 import models
    # queryset = models.PhoneTable.objects.all()
    # q1=models.PhoneTable.objects.filter(mobile='19912113111',id=8)
    # print(q1)
    # q2={"mobile":"19912113111","id":"8"}
    # q3=models.PhoneTable.objects.filter(**q2)
    # print(q3)
    # q4={}
    # q5=models.PhoneTable.objects.filter(**q4)
    # print(q5)
    # 从 GET 请求参数中获取名为 ‘page’ 的参数，如果没有提供，默认为1，并将其转换为整数类型。这个参数表示用户请求的页码。
    page = int(request.GET.get('page', 1))
    # 计算查询的起始索引和结束索引，用于分页查询数据
    start = int((page - 1) * 10)
    end = int(page * 10)
    page_size = 10
    # 从 GET 请求参数中获取名为 ‘q’ 的参数，如果没有提供，默认为空字符串。这个参数通常用于用户输入的搜索关键词。
    value = request.GET.get('q', "")
    na = {}
    if value:
        na["mobile__contains"] = value
    page_list = []
    # 根据查询条件统计符合条件的数据总数。
    count = models.PhoneTable.objects.filter(**na).order_by('-leval').count()
    # 根据数据总数和每页显示数量计算总页数。divmmod除法，求出商和余数
    total_page_count, div = divmod(count, page_size)
    print(total_page_count)
    # 计算出当前页的前5页和后5页
    plus = 3
    if total_page_count <= 2 * plus + 1:
        start_page = 1
        end_page = total_page_count + 1
    else:

        # 处理当前页面小于3时，不应该显示0，-1,最小值ing该是1
        if page <= plus:
            start_page = 1
            end_page = 2 * plus + 1
        else:
            # 判断当前页+5>总页码时
            if (page + plus) > total_page_count:
                start_page = total_page_count - 2 * plus + 1 + 1
                end_page = total_page_count + 1 + 1

            else:
                start_page = page - plus
                end_page = page + plus
    if div:
        total_page_count += 1

    #首页
    page_list.append('<li><a href="?page={}">首页</a></li>'.format(1))
    # 处理上一页
    if page > 1:
        prev = '<li><a href="?page= {}">上一页</a></li>'.format(page - 1)
        page_list.append(prev)
    else:
        prev = '<li><a href="?page= {}">上一页</a></li>'.format(page)
        page_list.append(prev)

    for i in range(start_page, end_page):

        if i == page:
            ele = '<li class="active"><a href="?page= {}">{}</a></li>'.format(i, i)
        else:
            ele = '<li><a href="?page= {}">{}</a></li>'.format(i, i)

        page_list.append(ele)


    # 处理下一页
    if page < total_page_count:
        prev = '<li><a href="?page= {}">下一页</a></li>'.format(page + 1)
        page_list.append(prev)
    else:
        prev = '<li><a href="?page= {}">下一页</a></li>'.format(page)
        page_list.append(prev)

    page_list.append('<li><a href="?page={}">尾页</a></li>'.format(total_page_count))

    page_string = mark_safe("".join(page_list))
    # 首页
    queryset = models.PhoneTable.objects.filter(**na).order_by('-leval')[start:end]
    # Choices are: id, leval, mobile, price, status
    return render(request, 'phone_list.html', {"queryset": queryset, "value": value, "page_string": page_string})


def phone_add(request):
    form = PhoneModelForm()
    if request.method == "GET":
        return render(request, 'phone_add.html', {"form": form})
    form = PhoneModelForm(data=request.POST)
    if form.is_valid():
        form.save()
        return redirect('/phone/list/')
    return render(request, 'phone_add.html', {"form": form})


def phone_edit(request, nid):
    row_object = models.PhoneTable.objects.filter(id=nid).first()
    if request.method == "GET":
        # 添加默认信息,modefrom把获取的值默认显示出来
        form = PhoneModelForm(instance=row_object)
        return render(request, "phone_edit.html", {"form": form, "nid": nid})
    form = PhoneModelForm(data=request.POST, instance=row_object)
    if form.is_valid():
        # 默认保存用户输入的数据
        form.save()
        return redirect('/phone/list/')
    return render(request, "phone_edit.html", {"form": form, "nid": nid})


def phone_del(request, nid):
    models.PhoneTable.objects.filter(id=nid).delete()
    return redirect("/phone/list/")

djangoProject2/app01/templates/depart_add.html
{% extends 'mom.html' %}
{% block content %}
<div>
    <div class="container">
        <div class="panel-body">
            <form method="post">
                {% csrf_token %}
                <div class="form-group">
                    <label>标题</label>
                    <input type="text" class="form-control" placeholder="添加部门标题" name="title">
                </div>
                <button type="submit" class="btn btn-primary">保 存</button>
            </form>
        </div>
    </div>
</div>
{% endblock %}

djangoProject2/app01/templates/depart_edit.html

{% extends 'mom.html' %}
{% block content %}
<div>
    <div class="container">

        <div class="panel-body">
            <form method="post">
                {% csrf_token %}
                <div class="form-group">.
                    <label>修改部门</label>
                    <input type="text" class="form-control" placeholder="标题" name="title" value="{{ row_object.title }}">
                </div>
                <button type="submit" class="btn btn-primary">保 存</button>
            </form>
        </div>
    </div>
</div>
{% endblock %}


djangoProject2/app01/templates/depart_list.html
{% extends 'mom.html' %}
{% block content %}
<div>
    <div class="container">
        <div style="margin-bottom: 10px">
            <a class="btn btn-success" href="/depart/add/">
                <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>
                新建部门
            </a>
        </div>

        <div class="bs-example" data-example-id="panel-without-body-with-table">
    <div class="panel panel-default">
      <div class="panel-heading">部门列表</div>
      <table class="table table-bordered" >
        <thead>
          <tr>
            <th>ID</th>
            <th>部门</th>
            <th>操作</th>
          </tr>
        </thead>
        <tbody>
        {% for obj in queryset %}
              <tr>
                <th>{{ obj.id }}</th>
                <td>{{ obj.title }}</td>
                <td>
                    <a class="btn btn-primary btn-xs" href="/depart/{{ obj.id }}/edit/">编辑</a>
                    <a class="btn btn-danger btn-xs" href="http://localhost:8000/depart/del/?nid={{ obj.id }}">删除</a>
              </tr>
        {% endfor %}
        </tbody>
      </table>
    </div>
  </div>
    </div>
</div>
{% endblock %}

djangoProject2/app01/templates/mom.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
    <style>
        .navbar {
            border-radius: 0;
        }
    </style>
</head>
<body>

<nav class="navbar navbar-default">
    <div class="container">
        <!-- Brand and toggle get grouped for better mobile display -->
        <div class="navbar-header">
            <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                    data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
                <span class="sr-only">Toggle navigation</span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
                <span class="icon-bar"></span>
            </button>
            <a class="navbar-brand" href="#">管理系统</a>
        </div>
        <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
            <ul class="nav navbar-nav">
                <li><a href="/depart/list/">部门管理</a></li>
                <li><a href="/user/list/">用户管理</a></li>
                <li><a href="/phone/list/">手机号管理</a></li>
                <li class="dropdown">
                    <ul class="dropdown-menu">


                    </ul>
                </li>
            </ul>
            <ul class="nav navbar-nav navbar-right">
                <li><a href="#">登录</a></li>
                <li class="dropdown">
                    <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true"
                       aria-expanded="false">杨振浩 <span class="caret"></span></a>
                    <ul class="dropdown-menu">
                        <li><a href="#">个人资料</a></li>
                        <li><a href="#">我的信息</a></li>
                        <li><a href="#">注销</a></li>
                        <li role="separator" class="divider"></li>
                        <li><a href="#">其他</a></li>
                    </ul>
                </li>
            </ul>
        </div><!-- /.navbar-collapse -->
    </div><!-- /.container-fluid -->
</nav>
<div>
    {% block content %}{% endblock %}
</div>

<script src="{% static 'js/jquery-3.5.1/jquery-3.5.1.min.js' %}"></script>
<script src="{% static 'js/bootstrap.min.js' %}"></script>

</body>
</html>

djangoProject2/app01/templates/phone_add.html
{% extends 'mom.html' %}
{% block content %}
    <div>
        <div class="container">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h3 class="panel-title" href="">新建号码</h3>
                </div>
                <div class="panel-body" >
                    <form method="post" novalidate>
                        {% csrf_token %}
                        {% for filed in form %}
                            <div class="form-group">
                                <label>{{ filed.label }}</label>
                                {{ filed }}
                                <span style="color: red;"> {{ filed.errors.0 }}</span>
                            </div>
                        {% endfor %}

                        <button type="submit" class="btn btn-primary" a>保 存</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}
<form method="post">
    {% csrf_token %}
    <!--
        {{ form.name.label }}: {{ form.name }}
        {{ form.passwd.label }}:{{ form.passwd }}
        {{ form.age.label }}:{{ form.age }}
        -->
    {% for i in form %}
        {{ i.label }}:{{ i }}
    {% endfor %}
</form>

djangoProject2/app01/templates/phone_edit.html
{% extends 'mom.html' %}

{% block content %}
      <div>
        <div class="container">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h3 class="panel-title">编辑手机号</h3>
                </div>
                <div class="panel-body" >
                    <form method="post" novalidate>
                        {% csrf_token %}
                        {% for filed in form %}
                            <div class="form-group">
                                <label>{{ filed.label }}</label>
                                {{ filed }}
                                <span style="color: red;"> {{ filed.errors.0 }}</span>
                            </div>
                        {% endfor %}

                        <button type="submit" class="btn btn-primary">保 存</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

djangoProject2/app01/templates/phone_list.html
{% extends 'mom.html' %}
{% block content %}
    <div>
        <div class="container">
            <div style="margin-bottom: 10px" class="clearfix">
                <a class="btn btn-success" href="/phone/add/">
                    <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>
                    新建号码

                </a>
                <div style="float: right;width: 300px">
                    <form method="get">
                        <div class="input-group">

                            <input type="text" name="q" class="form-control" placeholder="查找电话号码"
                                   value="{{ value }}">
                            <span class=" input-group-btn">
                            <button class="btn btn-default" type="submit">查找</button>
                            </span>

                        </div><!-- /input-group -->
                    </form>
                </div>
            </div>
            <div class="bs-example" data-example-id="panel-without-body-with-table">
                <div class="panel panel-default">
                    <div class="panel-heading">用户列表</div>
                    <table class="table table-bordered">
                        <thead>
                        <tr>
                            <th>ID</th>
                            <th>号码</th>
                            <th>价格</th>
                            <th>级别</th>
                            <th>状态</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for obj in queryset %}
                            <tr>
                            <td>{{ obj.id }}</td>
                            <td>{{ obj.mobile }}</td>
                            <td>{{ obj.price }}</td>
                            <td>{{ obj.get_leval_display }}</td>
                            <td>{{ obj.get_status_display }}</td>
                            <td>
                            <a class="btn btn-primary btn-xs" href="/phone/{{ obj.id }}/edit/">编辑</a>
                            <a class="btn btn-danger btn-xs" href="/phone/{{ obj.id }}/del">删除</a>
                        {% endfor %}
                        </tr>
                        </tbody>
                    </table>
                </div>

                <nav aria-label="Page navigation">
                    <ul class="pagination">
                        {{ page_string }}
                    </ul>


                </nav>
                <form method="get">
                    <div class="col-lg-6" style="width: 180px">
                        <div class="input-group">
                            <input type="text" name="page" class="form-control" placeholder="查找">
                            <span class="input-group-btn">
                            <button class="btn btn-default" type="submit">Go!</button>
                                </span>
                        </div>

                    </div>
                </form>
            </div>


        </div>

{% endblock %}

djangoProject2/app01/templates/user_add.html
{% extends 'mom.html' %}

{% block content %}
    <div>
        <div class="container">
            <div class="panel-body">
                <form method="post">
                    {% csrf_token %}
                    <div class="form-group">
                        <label>姓名</label>
                        <input type="text" class="form-control" placeholder="添加用户姓名" name="user">
                    </div>
                    <div class="form-group">
                        <label>密码</label>
                        <input type="text" class="form-control" placeholder="添加用户密码" name="pwd">
                    </div>
                    <div class="form-group">
                        <label>年龄</label>
                        <input type="text" class="form-control" placeholder="添加年龄" name="age">
                    </div>

                    <div class="form-group">
                        <label>余额</label>
                        <input type="text" class="form-control" placeholder="添加用户余额" name="count">
                    </div>
                    <div class="form-group">
                        <label>时间</label>
                        <input type="text" class="form-control" placeholder="添加用户入职时间" name="time">
                    </div>
                    <div class="form-group">
                        <label>性别</label>
                        <select class="form-control" name="sex">
                            {% for i in gender_choice %}
                                <option value="{{ i.0 }}">{{ i.1 }}</option>
                            {% endfor %}
                        </select>
                    </div>
                    <div class="form-group">
                        <label>部门</label>
                        <select class="form-control" name="bm">
                            {% for i in depart_list %}
                                <option value="{{ i.id }}">{{ i.title }}</option>
                            {% endfor %}
                        </select>
                    </div>

                    <button type="submit" class="btn btn-primary">保 存</button>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

djangoProject2/app01/templates/user_edit.html
{% extends 'mom.html'%}
{% block content %}
      <div>
        <div class="container">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h3 class="panel-title">编辑用户</h3>
                </div>
                <div class="panel-body" >
                    <form method="post" novalidate>
                        {% csrf_token %}
                        {% for filed in form %}
                            <div class="form-group">
                                <label>{{ filed.label }}</label>
                                {{ filed }}
                                <span style="color: red;"> {{ filed.errors.0 }}</span>
                            </div>
                        {% endfor %}

                        <button type="submit" class="btn btn-primary">保 存</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

djangoProject2/app01/templates/user_list.html
{% extends 'mom.html' %}
{% block content %}


    <div>
        <div class="container">
            <div style="margin-bottom: 10px">
                <a class="btn btn-success" href="/user/add/">
                    <span class="glyphicon glyphicon-plus" aria-hidden="true"></span>
                    新建用户
                </a>


                <a class="btn btn-success" href="/user/model_from_add/">
                    <span class="glyphicon glyphicon-plus-sign" aria-hidden="true"></span>
                    新建用户ModeFrim
                </a>
            </div>

            <div class="bs-example" data-example-id="panel-without-body-with-table">
                <div class="panel panel-default">
                    <div class="panel-heading">用户列表</div>
                    <table class="table table-bordered">
                        <thead>
                        <tr>
                            <th>ID</th>
                            <th>姓名</th>
                            <th>密码</th>
                            <th>年龄</th>
                            <th>余额</th>
                            <th>入职时间</th>
                            <th>性别</th>
                            <th>所属部门</th>
                            <th>操作</th>
                        </tr>
                        </thead>
                        <tbody>
                        {% for obj in queryset %}
                            <tr>
                            <td>{{ obj.id }}</td>
                            <td>{{ obj.name }}</td>
                            <td>{{ obj.passwd }}</td>
                            <td>{{ obj.age }}</td>
                            <td>{{ obj.account }}</td>
                            <td>{{ obj.creat_time | date:"Y-m-d" }}</td>
                            <td>{{ obj.get_gender_display }}</td>
                            <td>{{ obj.depart.title }}</td>

                            <td>
                            <a class="btn btn-primary btn-xs" href="/user/{{ obj.id }}/edit/">编辑</a>
                            <a class="btn btn-danger btn-xs" href="/user/{{ obj.id }}/del">删除</a>
                        {% endfor %}


                        </tr>
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
{% endblock %}

djangoProject2/app01/templates/user_model_from_add.html
{% extends 'mom.html' %}
{% block content %}
    <div>
        <div class="container">
            <div class="panel panel-default">
                <div class="panel-heading">
                    <h3 class="panel-title">新建用户</h3>
                </div>
                <div class="panel-body" >
                    <form method="post" novalidate>
                        {% csrf_token %}
                        {% for filed in form %}
                            <div class="form-group">
                                <label>{{ filed.label }}</label>
                                {{ filed }}
                                <span style="color: red;"> {{ filed.errors.0 }}</span>
                            </div>
                        {% endfor %}

                        <button type="submit" class="btn btn-primary">保 存</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
{% endblock %}
<form method="post">
    {% csrf_token %}
    <!--
        {{ form.name.label }}: {{ form.name }}
        {{ form.passwd.label }}:{{ form.passwd }}
        {{ form.age.label }}:{{ form.age }}
        -->
    {% for i in form %}
        {{ i.label }}:{{ i }}
    {% endfor %}
</form>